In [10]:
import numpy as np
import matplotlib.pyplot as plt
import math
from mpl_toolkits.mplot3d import Axes3D

In [11]:
## the goal here is to solve Ax=b for x

# sizes
m = 16
n = 10

# vector b
c = np.random.randn(m,1)

# matrix A
A = np.random.randn(m,n)

# solution using explicit inverse
x1 = np.linalg.inv(A.T@A) @ (A.T@c)

# python solution (better method)
x2 = np.linalg.solve(A.T@A,A.T@c)

# show that the results are the same
print(np.round(x1.T,3))
print(np.round(x2.T,3))

[[-0.309 -0.103  0.223 -0.358  0.316 -0.05   0.077  0.348 -0.553  0.362]]
[[-0.309 -0.103  0.223 -0.358  0.316 -0.05   0.077  0.348 -0.553  0.362]]


In [12]:
## geometric perspective in R^3

# matrix sizes
m = 3
n = 2

# vector b
b = np.random.randn(m,1)

# matrix A
A = np.random.randn(m,n)


# solution
x = np.linalg.solve(A.T@A,A.T@b)
Ax = A@x

print(b.T)
print(Ax.T)

[[-0.68411671  0.68703174  1.6646938 ]]
[[-0.88267756  0.04135151  1.57007043]]


In [ ]:
## plot

fig = plt.figure(figsize=plt.figaspect(1))
ax = fig.add_subplot(111, projection='3d')  # Add a 3D subplot

# plot the vectors
ax.plot([0, b[0]],[0, b[1]],[0, b[2]],'r')
ax.plot([0, Ax[0]],[0, Ax[1]],[0, Ax[2]],'b')

# plot the projection line
ax.plot( [Ax[0][0], b[0]],
         [Ax[1][0], b[1]],
         [Ax[2][0], b[2]], 'g')

# now draw plane
xx, yy = np.meshgrid(np.linspace(-2,2), np.linspace(-2,2))
cp = np.cross(A[:,0],A[:,1])
z1 = (-cp[0]*xx - cp[1]*yy)*1./cp[2]
ax.plot_surface(xx,yy,z1,alpha=.4)

plt.show()