# Code Challenge - RREF of Various Matrices 

In [1]:
import numpy as np
from sympy import *

In [2]:
m = 7
n = 5

# Square Matrix

Sq = Matrix(np.random.randn(m, m))

# Rectangular Matrix (Tall, Wide)

RT = Matrix(np.random.randn(m, n))
RW = Matrix(np.random.randn(n, m))

# RREF Calculations

rrefSq = Sq.rref()
rrefRT = RT.rref()
rrefRW = RW.rref()

# Linear Dependencies (Columns, Rows)

LDSq = Sq
LDSq[:, 1] = LDSq[:, 2]
rrefLDSq = LDSq.rref()


print(np.array(rrefSq[0]))
print(" ")
print(np.array(rrefRT[0]))
print(" ")
print(np.array(rrefRW[0]))
print(" ")
print(np.array(rrefLDSq[0]))

[[1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]
 
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]
 
[[1 0 0 0 0 -0.972160582358147 -0.204786031341552]
 [0 1 0 0 0 1.54782957727979 -0.168516297303204]
 [0 0 1 0 0 -0.668826988401669 -1.08901584538460]
 [0 0 0 1 0 -0.796958224942700 1.29105897071144]
 [0 0 0 0 1 1.12826306484853 0.0918916883832788]]
 
[[1 0 0 0 0 0 0]
 [0 1 1.00000000000000 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0]]
