In [ ]:
# Code Challenge : Matrix Multiplication Persepectives

In [ ]:
# implement matrix multiplication via layers

# generate two matrices (A, B)

# build the product matrix using layer-wise (for-loop)

# implement the matrix multiplication directly

# compare the matrix

In [1]:
import numpy as np

m = 3
n = 4

A = np.random.randn(m,n)
B = np.random.randn(n,m)

C1 = np.zeros((m,m))

for i in range(n):
    C1 = C1 + np.outer(A[:,i], B[i,:])

print(C1)

C2 = A@B
print(C2)

print(C1-C2)


[[ 0.36813215  0.23739859 -0.5503616 ]
 [-3.43661792  3.40935957 -1.63706922]
 [ 2.8532178  -1.92458668 -1.44600521]]
[[ 0.36813215  0.23739859 -0.5503616 ]
 [-3.43661792  3.40935957 -1.63706922]
 [ 2.8532178  -1.92458668 -1.44600521]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-4.44089210e-16  0.00000000e+00  2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]
