# Code Challenge: MCA Algorithm in Code

In [6]:
import numpy as np

# Compute the inverse using np.linalg.inv(), compare with your implementation of MCA

m = 4
A = np.random.randn(m, m)

# Initialise the Minors and H Matrix
minors = np.zeros((m, m))
H = np.zeros((m, m))

for i in range(m):
    for j in range(m):
        # Select the rows and columns
        rows = [True]*m
        rows[i] = False

        cols = [True]*m
        cols[j] = False

        # Compute the Minors Matrix
        minors[i, j] = np.linalg.det(A[rows,:][:,cols])

        # Compute the H Matrix
        H[i, j] = (-1)**(i+j)

# Cofactors Matrix Computation
cofactors = minors*H

Ainv = cofactors.T / np.linalg.det(A)
print(Ainv)
print(" ")

print(Ainv@A)
print(" ")

Ainv2 = np.linalg.inv(A)
print(Ainv2 - Ainv)

[[-0.36059758 -0.34565458  0.21575656 -0.41428809]
 [-0.64938143  0.10731946  0.42465081 -0.24909419]
 [ 0.20786994  0.22870454 -0.15808102 -0.14291274]
 [-0.29156302 -0.02704224 -0.44056032  0.29846114]]
 
[[ 1.00000000e+00  5.55111512e-17 -2.22044605e-16 -4.85722573e-17]
 [ 8.32667268e-17  1.00000000e+00  0.00000000e+00  3.12250226e-16]
 [-1.66533454e-16  5.55111512e-17  1.00000000e+00 -1.00613962e-16]
 [ 5.55111512e-17 -6.59194921e-17  1.11022302e-16  1.00000000e+00]]
 
[[-1.11022302e-16 -5.55111512e-17  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.38777878e-17  1.11022302e-16  5.55111512e-17]
 [ 5.55111512e-17 -2.77555756e-17 -8.32667268e-17 -5.55111512e-17]
 [-5.55111512e-17  2.08166817e-17 -5.55111512e-17  5.55111512e-17]]
