# Code Challenge: Diagonal Matrices and their Inverses

In [6]:
import numpy as np

# Create some diagonal matrices, start with 2x2 integers, work up to large matrices
# Compute their inverses (condition on the diagonal matrix for invertibility)

A = np.array([[2, 0], [0, 3]])
B = np.diag(np.arange(1, 6))
print(A)
print(" ")
print(B)
print(" ")

Ainv = np.linalg.inv(A)
Binv = np.linalg.inv(B)
print(Ainv)
print(" ")
print(Binv)
print(" ")
print(A@Ainv)
print(" ")
print(B@Binv)

[[2 0]
 [0 3]]
 
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
 
[[0.5        0.        ]
 [0.         0.33333333]]
 
[[ 1.          0.          0.          0.          0.        ]
 [ 0.          0.5         0.          0.          0.        ]
 [ 0.          0.          0.33333333  0.          0.        ]
 [-0.         -0.         -0.          0.25       -0.        ]
 [ 0.          0.          0.          0.          0.2       ]]
 
[[1. 0.]
 [0. 1.]]
 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
