# Code Challenge - QR and Least Squares

In [1]:
import numpy as np

In [3]:
# Generate random data (design matrix X, data y)

m = 10
n = 3

X = np.random.randn(10,3)
y = np.random.randn(10,1)
print(X)
print(" ")
print(y)
print(" ")

# Solve for beta using QR decomposition

Q, R = np.linalg.qr(X)
beta1 = np.linalg.solve(R.T@R, (Q@R).T@y)

# Compare the QR results with the standard "left-inverse" method
beta2 = np.linalg.solve(X.T@X, X.T@y)
beta2 = np.linalg.lstsq(X, y, rcond=None)[0]

print(beta1)
print(" ")
print(beta2)

[[-0.57961076  0.40750547 -1.56876847]
 [-1.40764492  0.63850444 -0.67921253]
 [ 0.16320975  0.29692506  0.60191053]
 [ 0.09698493 -0.95106481  2.35075362]
 [-0.53183944 -1.49533144  1.92408568]
 [-1.55247531 -1.92069644 -1.3062157 ]
 [-0.12518708  0.18525242  2.25164876]
 [ 0.68306852 -1.39924661 -0.09271782]
 [ 1.41755699  0.07996494  0.53318221]
 [-1.25554572  0.11996329 -0.52535002]]
 
[[ 1.08123688]
 [ 0.18564766]
 [-1.11305777]
 [ 0.367558  ]
 [-0.14719329]
 [ 0.74844401]
 [ 0.63307869]
 [ 1.28730439]
 [ 0.67325502]
 [-0.97139586]]
 
[[ 0.23413898]
 [-0.40969527]
 [-0.14755476]]
 
[[ 0.23413898]
 [-0.40969527]
 [-0.14755476]]
