In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sympy import *

In [2]:
m = 10
n = 3

# create data
X = np.random.randn(m,n) # "design matrix"
y = np.random.randn(m,1) # "outcome measures (data)"

np.shape(y)

(10, 1)

In [3]:
# try directly applying RREF
Xy = Matrix( np.concatenate([X,y],axis=1) )
print( Xy.rref() )

(Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0]]), (0, 1, 2, 3))


In [4]:
# now reapply to the normal equations
XtX = X.T@X
Xty = X.T@y
normEQ = Matrix( np.concatenate( [XtX,Xty],axis=1 ) )

Xsol = normEQ.rref()
Xsol = Xsol[0]
beta = Xsol[:,-1]

print(np.array(Xsol)), print(' ')
print(beta), print(' ')

# compare to left-inverse
beta2 = np.linalg.inv(XtX) @ Xty
print(beta2), print(' ')

# and with the python solver
beta3 = np.linalg.solve(XtX,Xty)
print(beta3)

[[1 0 0 0.179708899983792]
 [0 1 0 -0.272724845920517]
 [0 0 1 -0.0788072221450424]]
 
Matrix([[0.179708899983792], [-0.272724845920517], [-0.0788072221450424]])
 
[[ 0.1797089 ]
 [-0.27272485]
 [-0.07880722]]
 
[[ 0.1797089 ]
 [-0.27272485]
 [-0.07880722]]
