# Code Challenge: Is this vector in the span of this set?

In [4]:
import numpy as np

# determine whether this vector

v = np.array([[1, 2, 3, 4]]).T
# print(v)

# is in the span of these sets

S = np.vstack(([4, 3, 6, 2], [0, 4, 0, 1])).T
T = np.vstack(([1, 2, 2, 2], [0, 0, 1, 2])).T
print(S)
# print(T)

Sv = np.concatenate((S, v), axis = 1)
Tv = np.concatenate((T, v), axis = 1)
print(Sv)

print(np.linalg.matrix_rank(S))
print(np.linalg.matrix_rank(Sv))
print(np.linalg.matrix_rank(T))
print(np.linalg.matrix_rank(Tv))

[[4 0]
 [3 4]
 [6 0]
 [2 1]]
[[4 0 1]
 [3 4 2]
 [6 0 3]
 [2 1 4]]
2
3
2
2
