# Code Challenge: Large Matrices with row exchanges

In [7]:
import numpy as np

# generate a 6x6 matrix
 
A = np.random.randn(6, 6)
print(A)
print(" ")

# compute the determinant

print(np.linalg.det(A))
print(" ")

# one row exchange

A[:, [0, 1]] = A[:, [1, 0]]
print(A)
print(" ")
print(np.linalg.det(A))
print(" ")

# two row exchange

A[:, [1, 2]] = A[:, [2, 1]]
print(A)
print(" ")
print(np.linalg.det(A))


[[-0.68269793 -0.11068955  0.86549933 -1.74381358 -1.41671517 -0.41045977]
 [ 1.5112139  -0.29079552  0.83341     0.36201974  0.89232909 -0.95380444]
 [ 0.7322488   0.91689237 -0.53519082  0.60075897 -0.2575566   1.67321858]
 [ 0.29401454 -0.37579188 -0.07339008 -0.36488216  0.7519949  -0.18764121]
 [ 0.97084198 -2.4815233   0.33412757  1.02426737  0.79852805  1.05499259]
 [-0.43738737 -1.06508281 -1.44849187 -0.6101761   0.89669535 -1.07552755]]
 
-19.71229981190441
 
[[-0.11068955 -0.68269793  0.86549933 -1.74381358 -1.41671517 -0.41045977]
 [-0.29079552  1.5112139   0.83341     0.36201974  0.89232909 -0.95380444]
 [ 0.91689237  0.7322488  -0.53519082  0.60075897 -0.2575566   1.67321858]
 [-0.37579188  0.29401454 -0.07339008 -0.36488216  0.7519949  -0.18764121]
 [-2.4815233   0.97084198  0.33412757  1.02426737  0.79852805  1.05499259]
 [-1.06508281 -0.43738737 -1.44849187 -0.6101761   0.89669535 -1.07552755]]
 
19.71229981190441
 
[[-0.11068955  0.86549933 -0.68269793 -1.74381358 -1.