# Code Challenge: Determinant of small and large Matrices

In [29]:
import numpy as np

# singular matrices (reduced-rank matrices) have determinant equal to 0

# generate a 2x2 matrix with linear dependencies
A = np.round(10*np.random.randn(2, 2))
A[:,1] = A[:,0]
print(A)

# compute the determinant
x = np.linalg.det(A)
print(x)
print(" ")

# generate a mxm matrix with linear dependencies (with small and large m)
m = 12
B = np.round(10*np.random.randn(m, m))
B[:,1] = B[:,0]
print(B)

# compute the determinant
y = np.linalg.det(B)
print(y)

# Computer precision error causes the determinant to be larger as m increases

[[-4. -4.]
 [ 1.  1.]]
0.0
 
[[ -5.  -5.  21.  14.  15. -13.  -3.  17.   7.   9.  17.  -0.]
 [-22. -22.  -3.   4.   6. -31. -16.  -3.  -9.  15.   0.   3.]
 [-13. -13.  -6.  -4.   7.  14.  -7. -18.  -3.  -6.   2.  11.]
 [ -2.  -2. -16.   3. -10.  -7.  -2.  -2.  -6. -13.  -9.  -6.]
 [-15. -15. -17. -23.   2. -18. -10.  -1.   3.  15. -15. -10.]
 [ 15.  15.  -6.  -3.  10.   6. -15.  -1. -10.  -5.  -1. -10.]
 [  9.   9. -14.  -7.   2. -12. -14. -19.   2.  -8.   5.   7.]
 [  5.   5.  -4.   5.  -3.  -2.  14. -13.   4. -14.   0.  -9.]
 [ -3.  -3.  18.  -5. -14.  22.   0.   0. -16.  -0.  -2.  -0.]
 [ 10.  10.  11.   1.  -2.  -5.  -1. -24.  12.  -2.  11.  13.]
 [-17. -17.   7.  -3.   9.   2.  11.  -6.   3. -10.   0.  -9.]
 [ 14.  14.  22.   1.   6.   3.  -4.  10.   7.  -7.  -9.   4.]]
-2.0658249248594927
