Code Challenge : Cauchy-Schwarz

In [3]:
import numpy as np

# Create 3 vectors
a = np.random.randn(5)
b = np.random.randn(5)
c = np.random.randn(1)*a

print(a)
print(b)
print(c)

[-2.21627314 -0.4450577   0.94174896 -1.07912554 -0.36453781]
[ 1.08336841  0.21447606 -0.27879556 -0.69029559  1.17636693]
[-0.72089189 -0.14476487  0.30632469 -0.35100947 -0.11857399]


In [4]:
prod1 = abs(np.dot(a,b))
p1 = np.linalg.norm(a)*np.linalg.norm(b)
print(f"{prod1}  {p1}")

prod2 = abs(np.dot(a,c))
p2 = np.linalg.norm(a)*np.linalg.norm(c)
print(f"{prod2}  {p2}")

2.442964577282923  4.799317523524734
2.372611004890176  2.3726110048901754
