# Code Challenge Matrix Multiplication Linearity

In [1]:
# Check for some random MxN matrices whether s(A+B) = sA + sB

import numpy as np

M = 3
N = 4
A = np.random.randn(M, N)
B = np.random.randn(M, N)
s = 10
p = s*(A+B)
p1 = s*A
p2 = s*B
print(A)
print(" ")
print(B)
print(" ")
print(p)
print(" ")
print(p1)
print(" ")
print(p2)
print(" ")
print(p1+p2)

[[-0.77354545 -1.26072495 -0.6820658   1.12671456]
 [ 0.30860428 -1.23442112  0.62363161 -0.07588723]
 [ 0.27264343  2.45808833  0.29985323  0.26296374]]
 
[[1.7332994  0.90583011 1.00924166 0.22289428]
 [0.53936505 2.75817619 0.99247124 2.81714994]
 [1.5386302  0.74884544 1.48605562 0.10253155]]
 
[[ 9.59753949 -3.54894842  3.27175866 13.49608834]
 [ 8.47969326 15.23755071 16.16102851 27.41262715]
 [18.11273631 32.06933768 17.85908854  3.65495294]]
 
[[ -7.73545449 -12.60724953  -6.82065798  11.26714559]
 [  3.08604281 -12.34421122   6.23631612  -0.75887228]
 [  2.72643434  24.58088326   2.99853233   2.6296374 ]]
 
[[17.33299398  9.05830111 10.09241664  2.22894276]
 [ 5.39365046 27.58176192  9.92471239 28.17149943]
 [15.38630197  7.48845443 14.86055621  1.02531554]]
 
[[ 9.59753949 -3.54894842  3.27175866 13.49608834]
 [ 8.47969326 15.23755071 16.16102851 27.41262715]
 [18.11273631 32.06933768 17.85908854  3.65495294]]
