In [ ]:
# Code Challenge Trace Operation Linearity

In [ ]:
# Determine the relationship between tr(A) + tr(B) and tr(A+B)
# Determine the relationship between tr(l*A) and l*tr(A)

In [2]:
import numpy as np

A = np.random.randn(4,4)
B = np.random.randn(4,4)
print(A)
print(' ')
print(B)
print(" ")

trA = np.trace(A)
trB = np.trace(B)
print(trA, trB)
print(" ")
print(trA+trB)
print(" ")
print(np.trace(A+B))
print(" ")

l = 7
print(np.trace(l*A))
print(" ")
print(l*(np.trace(A)))

[[ 0.47552376  2.01780786 -0.76289752  1.14115175]
 [ 0.46159956  2.26852803 -1.5467507   0.24638033]
 [ 0.28177271  0.98356962 -1.1981986   0.37489719]
 [-2.57388488 -2.42406509  0.95951086 -0.92476351]]
 
[[ 0.65300429  1.5487698  -0.21642573  0.06907754]
 [ 0.88358089  0.31429162  0.24580617 -0.33791438]
 [ 1.67390819 -0.10842615  2.11634162 -0.08858634]
 [-0.0307246  -1.41676454 -1.23140462  1.95638048]]
 
0.6210896845043617 5.040018011617599
 
5.661107696121961
 
5.661107696121961
 
4.347627791530531
 
4.347627791530532
