In [ ]:
# Code Challenge - Standard and Hadamard Multiplication of Diagonal Matrices

In [4]:
import numpy as np

# Create two matrices (4x4) : "Full" and "Diagonal"

A = np.round(10*np.random.randn(4, 4))
B = np.diag([2, 4, 6, 8])
print(A)
print(" ")
print(B)
print(" ")

# Multiply each matrix by itself : Standard and Hadamard Multiplication

AAst = A@A
AAHa = A*A
BBst = B@B
BBHa = B*B

print(AAst)
print(" ")
print(AAHa)
print(" ")
print(BBst)
print(" ")
print(BBHa)

[[ 15.   1.   1.   0.]
 [-14. -30. -11.   5.]
 [ 23.  -6.  -6.   4.]
 [  3.  15.  -6. -12.]]
 
[[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]
 
[[ 234.  -21.   -2.    9.]
 [ -28. 1027.  352. -254.]
 [ 303.  299.  101. -102.]
 [-339. -591.  -54.  195.]]
 
[[225.   1.   1.   0.]
 [196. 900. 121.  25.]
 [529.  36.  36.  16.]
 [  9. 225.  36. 144.]]
 
[[ 4  0  0  0]
 [ 0 16  0  0]
 [ 0  0 36  0]
 [ 0  0  0 64]]
 
[[ 4  0  0  0]
 [ 0 16  0  0]
 [ 0  0 36  0]
 [ 0  0  0 64]]
