In [ ]:
# Code Challenge - Symmetry of combined symmetric matrices

In [2]:
import numpy as np

# Create two symmetric matrices

A = np.array([[1 , 2, 3], [2, 4, 5], [3, 5, 6]])
B = np.array([[7, 8, 9], [8, 5, 2], [9, 2, 3]])

# Compute Sum, Multiplication, and Hadamard Multiplication of the two matrices
Sum = A+B
Multi = A@B
Hada = A*B

# Determine whether the result is a symmetric matrix or not
print(Sum-Sum.T)
print(Multi-Multi.T)
print(Hada-Hada.T)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[  0 -67 -93]
 [ 67   0 -20]
 [ 93  20   0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
